### ISSUE TITLE
create-from-yaml.py

### ISSUE THREAD

**Issue by MarcoSchaar** [rundeck-plugins/kubernetes#13]
hi,
got an error like this
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.7/create-from-yaml.py", line 114, in <module> main()
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.7/create-from-yaml.py", line 96, in main
print("Secret created '%s'" % str(resp.status))
AttributeError: 'V1Secret' object has no attribute 'status'

**Comment by MarcoSchaar** [comment]
Hi @ltamaster ,
thanks for looking into this ...
my yaml looks like this ... 

`apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ""
type: kubernetes.io/dockerconfigjson`

kind regards
Marco

**Comment by ltamaster** [comment]
Hi @MarcoSchaar 

It was fixed on 1.0.8.

Please let me know if worked for you

Thanks
Luis

**Comment by MarcoSchaar** [comment]
Thanks @ltamaster 
fixed version works well 👍
