### ISSUE TITLE
Create job with Persistent Volume

### ISSUE THREAD

**Issue by pavel-saltykov** [rundeck-plugins/kubernetes#15]
When i create Job with Persistent Volume,  plugin try take data for this from Resource Requests field. Version 1.07-SNAPSHOT
I see the following lines in log:

```
'volume_mounts': [{'mount_path': '1,memory=512Mi',
                'mount_propagation': None,
                'name': 'cpu',
                'read_only': None,
                'sub_path': None}],

ERROR: kubernetes-model-source: Exception creating job: (422)
Reason: Unprocessable Entity
```
In plugin source, file [ job-create.py](https://github.com/rundeck-plugins/kubernetes/blob/master/contents/job-create.py)

```
    if "volumes" in data:
        volumes_array = data["resources_requests"].splitlines()
```

**Comment by ltamaster** [comment]
Hey @pavel-saltykov ,

Can you share your job to reproduce it?

Thanks
Luis

**Comment by ltamaster** [comment]
Hi @pavel-saltykov,

I added a new release that includes the volume and volume-mount for create-jobs.

Please let me know if this fix this issue.

Thanks
Luis
