### ISSUE TITLE
create custom resource

### ISSUE THREAD

**Issue by MarcoSchaar** [rundeck-plugins/kubernetes#16]
Hi @ltamaster 
Is there a possibility to create a custom resource with a deployment job?
like command line 'kubectl create -f file.yaml'
kind regards
Marco

**Comment by ltamaster** [comment]
Hi @MarcoSchaar ,

Did you try with `Kubernetes / Generic / Create` ?

Luis

**Comment by MarcoSchaar** [comment]
Hi @ltamaster,
I've tried that way to setup something like https://github.com/Dynatrace/dynatrace-oneagent-operator#create-oneagent-custom-resource-for-oneagent-rollout

and got a error like

"message": "OneAgent in version \"v1alpha1\" cannot be handled as a Deployment: no kind \"OneAgent\" is registered for version \"dynatrace.com/v1alpha1\""

better to go with kubectl in such case?

**Comment by ltamaster** [comment]
Hi @MarcoSchaar,

This plugin is based on the kubernetes python library, and it doesn't have support to that API.
Your best chance now is to use kubectl.

Luis

**Comment by cesarcorreabedoya** [comment]
Hi @ltamaster 
¿do you happen to know if the  kubernetes python library supports the apiVersion: k6.io/v1alpha1 as I am needing to create the custom resource for k6 ?(check this out https://k6.io/blog/running-distributed-tests-on-k8s/).

if dont,  then , ¿how can I create a step that be able to run` kubectl apply -f /path/to/our/k6/custom-resource.yml`

Gracias Luis!
