### ISSUE TITLE
Not possible to use nodeSelector in create deployment

### ISSUE THREAD

**Issue by prasadasokan** [rundeck-plugins/kubernetes#21]
When trying to use nodeSelector in the yaml string section of a create deployment step, it is failing.

**Comment by ltamaster** [comment]
Hi @prasadasokan,

Can you share your job or the error?

Thanks
Luis

**Comment by prasadasokan** [comment]
The issue has been resolved after we made use of the latest plugin. Marking it as closed. Thanks @ltamaster
