### ISSUE TITLE
Support configMaps

### ISSUE THREAD

**Issue by umomany** [rundeck-plugins/kubernetes#24]
why isn't there any support in this plugin to create/delete config maps ?

**Comment by ltamaster** [comment]
You can use the generic create/delete workflow steps, is that OK for you?

<img width="964" alt="Screenshot 2019-04-11 12 03 24" src="https://user-images.githubusercontent.com/6034968/55972619-d52b4580-5c51-11e9-8167-9a66cc5bff94.png">
