### ISSUE TITLE
Support private registry

### ISSUE THREAD

**Issue by nickvth** [rundeck-plugins/kubernetes#34]
In order to use a private docker registry it's needed to specify the ImagePullSecrets
Support for job and deployment

**Comment by nickvth** [comment]
You can use Environment Variables from secret:

Key:Value

ImagePullSecrets=[registry-secret]

**Comment by nickvth** [comment]
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1PodSpec.md

image_pull_secrets

**Comment by robinv** [comment]
I would also really appreciate having support for defining imagePullSecrets.
Is there any chance we can get that?

**Comment by tholok97** [comment]
We would love this as well. All our images are in private registries so we can't try this plugin until imagePullSecrets is supported

**Comment by tholok97** [comment]
In case it's helpful to someone: Managed to circumevent this by using the "Kubernetes / Generic / Create" step type and manually typing the Deployment YAML including `imagePullSecrets`.
