### ISSUE TITLE
The gradle  build failed

### ISSUE THREAD

**Issue by RanganathNangineni** [rundeck-plugins/kubernetes#39]
Hi 

I have installed the kubernetes SDK and  trying to create the zip file for kubernetes plugin using gradle build but it is failing.

# gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/root/kubernetes/build.gradle' line: 7

* What went wrong:
Plugin [id: 'pl.allegro.tech.build.axion-release', version: '1.7.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'pl.allegro.tech.build.axion-release:pl.allegro.tech.build.axion-release.gradle.plugin:1.7.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s

**Comment by RanganathNangineni** [comment]
My grdle version 
]# gradle -v

------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_212 (Oracle Corporation 25.212-b04)
OS:           Linux 4.1.12-124.27.1.el7uek.x86_64 amd64

**Comment by tholok97** [comment]
Hi, I had issues with Gradle as well. You could try running it via a Docker container. This way you at least avoid any issues with your Gradle installation:
```
docker run -v "$PWD":/code gradle:4.7 gradle --project-dir /code build
```
(Realize this is an old issue, but just in case anyone else is fighting Gradle)

**Comment by ltamaster** [comment]
did you try with `gradlew`?
