### ISSUE TITLE
stderr breaks the script step

### ISSUE THREAD

**Issue by hdimitriou** [rundeck-plugins/kubernetes#43]
Using the script step to execute on a pod, I noticed that even though the commands returned with exit code 0, the job failed. 

I isolated the issue to commands that write to stderr without failing, like 'git clone' or even 'set -x' 

I would understand the logic, but shouldn't be a way around this?

**Comment by tholok97** [comment]
Maybe introduce a "fail script on stderr" option?

**Comment by ltamaster** [comment]
it should be fixed with https://github.com/rundeck-plugins/kubernetes/pull/51
