### ISSUE TITLE
Using kubeconfig in Workflow steps

### ISSUE THREAD

**Issue by kawaja** [rundeck-plugins/kubernetes#5]
I have been trying to use a kube config file in Workflow steps to authenticate against my kubernetes cluster. Looking through the code, it appears the functionality has been implemented (`$RD_CONFIG_CONFIG_FILE`), but the text field "Kubernetes Config File Path" doesn't exist to enter it.

I've submitted a PR to include "Kubernetes Config File Path" in each Workflow step configuration.

**Comment by ltamaster** [comment]
Thanks @kawaja I merged the PR

Luis
