### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by aliksend** [rundeck-plugins/kubernetes#50]
Hi

When is the next release scheduled? There is some bug fixes in master (like https://github.com/rundeck-plugins/kubernetes/pull/40), I need it in my setup. 
Is master stable? If it is hard to make release, can I build plugin and use it in production? Is there new bugs after last release?

Thank you

**Comment by ltamaster** [comment]
done
https://github.com/rundeck-plugins/kubernetes/releases/tag/1.0.13

**Comment by aliksend** [comment]
Thank you very much
