### ISSUE TITLE
Create deployment = 404 not found

### ISSUE THREAD

**Issue by yohan212** [rundeck-plugins/kubernetes#65]
Hello guys,
I have some trouble to create a deployment with the node step. 
I can create pods, services but I have 404 error when I try to create a deployment. 

Have ever seen that ? 

Thank's for your help

**Comment by prasadasokan** [comment]
We are running into the same issue as well. We upgraded to 1.0.17 after upgrading our k8s clusters to 1.18.3. Does the plugin support k8s v1.18.3?

**Comment by jonathan-mothership** [comment]
Could be fixed in https://github.com/rundeck-plugins/kubernetes/pull/72
