### ISSUE TITLE
Regression in wait-for-job: Bad Request

### ISSUE THREAD

**Issue by jonathan-mothership** [rundeck-plugins/kubernetes#70]
We use the custom resource steps to:
1) create a new job
2) wait for the job completion and spit out the logs
3) delete the job resource

It seems upgrading from version 15 to 16 there was a regression that causes the Job/Waitfor step to error on pulling logs when the pod is spinning up. 

Debug logs:
```
...
DEBUG: kubernetes-wait-job: Searching for pod associated with job
DEBUG: kubernetes-wait-job: Fetching logs from pod: rundeck-test-blah-9548-86vwq
INFO: kubernetes-wait-job: ========================== job log start ==========================
ERROR: kubernetes-wait-job: Exception waiting for job: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1525ec26-f329-4675-800e-4d03061fd3be', 'Content-Type': 'application/json', 'Date': 'Wed, 24 Jun 2020 22:22:22 GMT', 'Content-Length': '221'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \\"tests\\" in pod \\"rundeck-test-blah-9548-86vwq\\" is waiting to start: ContainerCreating","reason":"BadRequest","code":400}\n'
```

**Comment by wadelu** [comment]
Hi Team,
The same issue faced, how to resolve it?

**Comment by wadelu** [comment]
Checking job status ...
--
09:21:05 |   | ERROR: kubernetes-wait-pod: Exception waiting for job: (401)
09:21:05 |   | Reason: Unauthorized
09:21:05 |   | HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Length': '165', 'Audit-Id': '3b7692d2-d1f0-4420-90ce-9cdd8f3f802a', 'Content-Type': 'application/json', 'Date': 'Thu, 29 Oct 2020 09:21:05 GMT'})
09:21:05 |   | HTTP response body: {
09:21:05 |   | "kind": "Status",
09:21:05 |   | "apiVersion": "v1",
09:21:05 |   | "metadata": {
09:21:05 |   |  
09:21:05 |   | },
09:21:05 |   | "status": "Failure",
09:21:05 |   | "message": "Unauthorized",
09:21:05 |   | "reason": "Unauthorized",
09:21:05 |   | "code": 401
09:21:05 |   | }
09:21:05 |   |  
09:21:05 |   |  
09:21:05 |   | Failed: NonZeroResultCode: Script result code was: 1

**Comment by jonathan-mothership** [comment]
That's a different issue than the one reported here. The original report is a 400 error caused by a malformed request and your error is 401, likely caused by authentication or RBAC.
