### ISSUE TITLE
Wait For Job

### ISSUE THREAD

**Issue by majgis** [rundeck-plugins/kubernetes#9]
I see the `Kubernetes / Deployment / Waitfor` task.
I have assumed this can't be used to wait for a Job just created to complete, is that correct?

Would a feature `Kubernetes / Job / Waitfor` that waits for a job to complete, make sense for general usage?  
A bonus would be also reporting the log to rundeck.

**Comment by majgis** [comment]
I created a python script using the same kubernetes library used by this plugin.  It worked to wait for the job to complete and extract job status.  It looks like the best way to pass the token is to incorporate this script in a plugin.

Does a step to wait for job make sense to add to this plugin, or should I go off on my own?  If this feature does work well with this library, would you consider a PR from me or is it something you would consider doing?

**Comment by ltamaster** [comment]
Hi @majgis ,

Yes, it makes sense, we will consider off course.

Luis

**Comment by majgis** [comment]
Thanks.  I'm digging into this problem just now, so I'll make sure to extend this plugin and submit a PR.  
I'll mimic as closely as possible what was done in `/Deployment / Waitfor` and extract to common.py if it makes sense.
